version: '3.7'
services:

  caddy:
    image: abiosoft/caddy:no-stats
    restart: always
    networks:
      internal:
        aliases:
          - front.internal
    environment:
      ACME_AGREE: 'true'
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./data:/root/.caddy

networks:
  internal:
